### ISSUE TITLE
Failed to complete volume division in dotify:obfl-to-pef

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#118]
Error reported by @matskober .

Volume division error generated by `dotify:obfl-to-pef` when using a modified version of book 118883.

The equivalent EPUB does not give this error (when converting with the nordic migrator).

@josteinaj will create a xprocspec test case.

**Comment by josteinaj** [comment]
@matskober after upgrading the server, the job results were lost, and I can't see what options you used when converting the book. Can you create a new job which reproduces this error?

**Comment by josteinaj** [comment]
@matskober never mind, I got it reproduced.

Added test in 14f8a80fc193012e5962caba82d7b57abef98e8a.

**Comment by bertfrees** [comment]
Should have been fixed now. The test that Jostein provided is really an extreme case I think, and it requires 23 iterations. I have some ideas to further improve things if needed, and we can possibly also increase the maximum number of iterations.

**Comment by josteinaj** [comment]
When we tested before summer, I think we found that the iterations doesn't really take much time, so a high limit may not be a problem. Maybe the [max iterations limit](https://github.com/nlbdev/pipeline/commit/a73769d75e0f431139172726218afae9f15784fb#diff-71666b522dd12e736f49b9caac6750bbR135) could be replaced by a timeout of 2 minutes or something?

**Comment by bertfrees** [comment]
No, a high limit is not necessarily a problem. But it does point out problems in the algorithm. That's what the limit is for, to detect when algorithm does not converge (fast enough) to a solution. That's why I like to set it just high enough, so that we are warned and we can optimize the algorithm.

A timeout is an interesting idea but in the end it just comes down to the same thing I think. The difference is that you can set it to a value that is acceptable for a user to wait, but it just comes down to setting a higher iterations limit. Dunno. @joeha480 what do you think?

**Comment by josteinaj** [comment]
@matskober is still getting this error, so I've created a new test based on an obfuscated version of a real book instead of generating it like in the previous test:

https://github.com/nlbdev/pipeline/commit/73aad642d8ba56dbc353b7918c6b3084257b210a#diff-0ffc6ea8a876071ea0723b93bba79ecaR1054

**Comment by bertfrees** [comment]
OK I'll look at it again.

**Comment by bertfrees** [comment]
Did some more fixes.

**Comment by matskober** [comment]
Seem to work now.

**Comment by joeha480** [comment]
We could make the number of iterations configurable and keep the default to around 10-20. Like Bert said, a very high number indicates some problem with the algorithm, but if you just want to get the book through, you could increase it manually (but report it for debugging later).
