### ISSUE TITLE
No default braille character for other languages, causing ⡳ to be included in 6-dot

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#146]
DTBook in englig, with "Alltid norsk" unchecked, produces a pef with '8-dot: YES' 
[error_8-dot.zip](https://github.com/nlbdev/pipeline/files/1482242/error_8-dot.zip)
@bertfrees @josteinaj

**Comment by josteinaj** [comment]
@matskober Your attachment doesn't look like 8-dot braille to me. But I only skimmed through it. Is it only specific parts of the output that becomes 8-dot? Is there a job on the test server that I can look at?

**Comment by matskober** [comment]
I know, it does look okay. But e2u says it contains 8-dots.

**Comment by josteinaj** [comment]
These are all the uniqe braille characters used in your attachment:

```
⠀⠠⠛⠑⠕⠗⠇⠊
⠞⠓⠍⠝⠋⠎⠃⠤
⠼⠚⠁⠥⠅⠧⠉⠏
⠲⠙⠒⠈⠺⠄⠽⠭
⠵⠿⠂⠐⠆⠰⠣⠜
⠟⠦⠶⠸⠌⠘⠴⠩
⠖⠯⠨⠹⠡⡳⠢⠱
⠔
```

I see that this character is used in some places: `⡳`.

I can't make sense of the braille so I don't know what the input text was, but I see that several languages, including norwegian, use this braille character for "latin capital letter u with diaeresis".

I will try to reproduce it in a test.

**Comment by josteinaj** [comment]
Ok, it seems to be due to characters that are not defined in any table, and so they default (as I understand it) to a braille representation of the unicode number for that character.

For instance:
```
ɐ ⇒ ⠄⡳⠭⠴⠆⠢⠴⠄
ɑ ⇒ ⠄⡳⠭⠴⠆⠢⠂⠄
ɒ ⇒ ⠄⡳⠭⠴⠆⠢⠆⠄
ɓ ⇒ ⠄⡳⠭⠴⠆⠢⠒⠄
ɔ ⇒ ⠄⡳⠭⠴⠆⠢⠲⠄
ɕ ⇒ ⠄⡳⠭⠴⠆⠢⠢⠄
```

In the norwegian 6-dot table [we have this](https://github.com/liblouis/liblouis/blob/ddd8053abd3f1153af0daf788f24b1a07385e80e/tables/no-no-chardefs6.uti#L191) which is probably why you see this only when using `force-norwegian=false`:
```
undefined 26                 #sign used for undefined characters
```

@bertfrees would it be possible to use dot 26 for all undefined characters regardless of what table is used? Or at least for those tables where the opcode `undefined` is not used?

**Comment by bertfrees** [comment]
It is possible to use dot 26 for undefined characters. To let it depend on whether an `undefined` rule already exists is harder (and also makes less sense IMO).

**Comment by josteinaj** [comment]
Ok, always using dot 26 regardless of whether `undefined` would be fine.

**Comment by bertfrees** [comment]
This can be done by wrapping `liblouisTranslatorProvider` in `NLBTranslator` into a provider that prepends or appends this small table to every table:

```
undefined 26
```

**Comment by matskober** [comment]
Seems to be greek? So it should heve been marked up with xml:lang="el"; would that have made any difference?

**Comment by josteinaj** [comment]
@matskober Maybe, but there's still an issue with undefined characters.

**Comment by bertfrees** [comment]
Done
