### ISSUE TITLE
Fix script option: sheets/pages (default value and terminology)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#15]
_From @KariRudjord on June 10, 2016 7:32_

Change from sheets to pages i GUI. Maximum pages should be 86 (Jostein).
Keep sheets in CSS Sheets should be 43 (Ammar). 
Total amount of pages must be pages, not sheets. (Ammar/Bert)

We will communicate this to braille producers. It will only be a challenge when printing on every second page, and that we don't do often.

@josteinaj @usama49 @bertfrees 

_Copied from original issue: nlbdev/pipeline-mod-nlb#52_

**Comment by josteinaj** [comment]
_From @bertfrees on June 10, 2016 11:16_

- [x] Total amount of pages must be pages, not sheets: see https://github.com/snaekobbi/pipeline-mod-nlb/issues/32#issuecomment-225145600
- [x] Change from sheets to pages in GUI: This requires a change in the script (new option) and in the CSS (new option must be divided by 2 to obtain the value for max-length. The only difficulty is that in order to be able to add a new option to the script, you'll have to use the lower-level steps `px:dtbook-to-pef.convert` and `px:dtbook-to-pef.store`. There is an example of how to do this in mod-sbs: https://github.com/snaekobbi/pipeline-mod-sbs/blob/master/src/main/resources/xml/dtbook-to-pef.xpl (**EDIT**: this is now done in NLB script too).

**Comment by josteinaj** [comment]
...need to check if sheets/pages are used correctly in web ui.

**Comment by josteinaj** [comment]
@matskober is the terminology in the script correct? sheets/pages, hefter/sider, in the script options?

**Comment by matskober** [comment]
I thought pages where sufficient; why do we need sheets at all? (Is not the pef supposed to printer neutral; if not the only (paper) sheets relevant is 4 pages pr sheet - that's what NbFT uses.)

**Comment by bertfrees** [comment]
CSS and OBFL think in terms of sheets, so if you want pages this number needs to be divided by 2 internally (see also my comment above).

**Comment by josteinaj** [comment]
Currently it looks like this:

![sheets-pages-option](https://user-images.githubusercontent.com/295481/27950234-d771e200-6300-11e7-8112-905d7da0b439.png)

So the option name refers to pages, but the description refers to sheets.

**Comment by bertfrees** [comment]
Ideally you should create a new option (different name and description).

**Comment by matskober** [comment]
I'm confused by this issue; I have asked @bertfrees about this earlier - he said that the number inserted was referring to sheets. (In the sense that one sheet is two pages, a front page and a back page.) But to me it seems more appropriate to only talk about pages, not sheets. The need to control a page's appearance in the volume, e.g. whether it's a right hand or left hand page (or an odd- or  even numbered page, if you like), seems to be more in the spirit of the pef-format.

And since the current embossers used on NLBs pef-files have sheets consisting of four pages, we will be operating with two different sets of sheets; the the two sided "digital sheet" in PIP, and the four sided sheet from "real life". If anything, it would make more sense to refer to the four side sheet, since the limitations is a "real life"-issue, not a digital one. But the embosser neutral solution would be "max pages".    @josteinaj  @KariRudjord @usama49

**Comment by KariRudjord** [comment]
For me this seems OK now. But I would like you to have a look at it too, @matskober just to be sure. OK?

**Comment by KariRudjord** [comment]
OK

**Comment by josteinaj** [comment]
Since it's done i think this should be closed.
