### ISSUE TITLE
Improve preview

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#153]
- render æøåÆØÅ properly
- render numbers as numbers
- not all braille characters needs to be translated to ascii. For instance modifiers like the number sign, captial letter sign

**Comment by josteinaj** [comment]
I did a little experiment earlier this week. Not sure if it's the right way to approach this issue or not, but I've pushed it here for reference: 9e43bca0bbc6bbe2cbee2172cf50c4c77485e7d8

**Comment by matskober** [comment]
You mean to keep "generated" braille as braille in preview?

**Comment by bertfrees** [comment]
This is one approach, yes. I see you copied the code from [NabccEightDotTableProvider.java](https://github.com/daisy/pipeline-mod-braille/blob/develop/pipeline-braille-utils/liblouis-utils/liblouis-formatter/src/main/java/org/daisy/pipeline/braille/pef/impl/NabccEightDotTableProvider.java) and then changed the mapping to (x) <-> (2800 + x). I presume you have yet to change that mapping?

If I were to write such a table now myself I would probably do it with Liblouis instead of BrailleUtils. I wrote that NABCC table back when Liblouis tables were not yet supported. The same table looks like this in Liblouis: https://github.com/liblouis/liblouis/blob/master/tables/text_nabcc.dis

Here is the table that SBS uses for the preview: https://github.com/sbsdev/pipeline/blob/sbs/modules/sbs/braille-tables/src/main/resources/tables/sbs.dis

> render numbers as numbers

What exactly do you mean by that? Do you mean that the number 123 in braille (⠼⠁⠃⠉) should be rendered as `#123` while abc in braille (also ⠁⠃⠉) should be rendered as `ABC`? That would be an interesting idea. One option would be to add dot 7 or 8 to the digits (⠼⡁⡃⡉) so that they can be rendered differently in the preview, and drop dots 7 and 8 again at the time the PEF is printed. The problem with this is of course that in some cases it may not be desired to drop dots 7 and 8.

Liblouis expands on this idea with its concept of virtual dots. With virtual dots added you have 14 dots at your disposal (16384 combinations) instead of the regular 8 dots (256 combinations). At the moment this is not usable outside of Liblouis though. A PEF only allows the 256 normal braille patterns at the moment and the same is true for braille CSS. (Not sure about OBFL.)

**Comment by josteinaj** [comment]
> I presume you have yet to change that mapping?

Yes.

> Here is the table that SBS uses for the preview

Interesting, that's probably the way to go for us as well then? At least for letters like ÆØÅ? Could liblouis back-translation rules be used for rendering numbers in such a table?

> Do you mean that the number 123 in braille (⠼⠁⠃⠉) should be rendered as #123 while abc in braille (also ⠁⠃⠉) should be rendered as ABC?

Yes. It would be fairly simple to implement in Java, XSLT or whatever by iterating over the characters, looking for ⠼, and replacing abcdefghij with 1234567890.

I'm pretty confident I could do this as a post-processing step by passing the preview through an XSLT, but I wanted to see if there was a "proper" way of doing it first.

**Comment by bertfrees** [comment]
Yes it should be possible to do in a post-processing step. The proper way is to do it in Liblouis the way I described above, but at the moment we can't. So I'm not sure what to do. A post-processing step is a bit of a hack and to do it the proper way may require considerable changes.

**Comment by josteinaj** [comment]
Doing it in post-processing should be pretty straight forward, so I guess that would be fine for now.

**Comment by bertfrees** [comment]
The following changes are required to make the system not specific to Unicode braille:
- braille CSS: Make a definition of "braille" that does not impose an encoding. Currently "Unicode" braille is used in the specification. It should also be allowed to have different character codes for the same braille pattern (cfr. "extended braille"). Unicode braille is currently used in the following sections:
  - [4. Values and Units](http://braillespecs.github.io/braille-css/#h2_values-and-units), in the definition of [&lt;braille-character&gt;](http://braillespecs.github.io/braille-css/#dfn-braille-character) which is used in [borders](http://braillespecs.github.io/braille-css/20161201/#h3_the-border-properties), [`hyphenate-character`](http://braillespecs.github.io/braille-css/#dfn-hyphenate-character), [`list-style-type`](http://braillespecs.github.io/braille-css/#dfn-list-style-type) and [`leader()`](http://braillespecs.github.io/braille-css/#dfn-leader)
  - [10. Text](http://braillespecs.github.io/braille-css/#h2_text)
  - [10.1. Transforming Text](http://braillespecs.github.io/braille-css/#the-text-transform-property)
  - [10.10. Letter Spacing](http://braillespecs.github.io/braille-css/#h3_letter-spacing-the-letter-spacing-property), in the explanation of the "base unit"
  - [11.2.4. Defining Counter Styles](http://braillespecs.github.io/braille-css/#h4_defining-counter-styles-the-counter-style-rule)
- PEF: either we need to extend PEF to allow other characters than the ones in the 2800-28FF Unicode range, but I think that's unlikely to happen because the Unicode unambiguity thing is the essence of PEF. The alternative is to use a different output format, i.e. a different "media writer" in Dotify.
- OBFL and Dotify: nothing needs to change here I think (except the new media writer mentioned above but that would be a Dotify plugin)
- Pipeline braille modules:
  - Don't use 2800-28FF range in ~~`org.daisy.pipeline.braille.dotify.impl.BrailleFilterFactoryImpl` (["BRAILLE"](https://github.com/daisy/pipeline-mod-braille/blob/c6f8e173ecf270d041d02ef6cc0300a45c9f58e0/pipeline-braille-utils/dotify-utils/dotify-formatter/src/main/java/org/daisy/pipeline/braille/dotify/impl/BrailleFilterFactoryImpl.java#L231) and ["VALID_INPUT"](https://github.com/daisy/pipeline-mod-braille/blob/c6f8e173ecf270d041d02ef6cc0300a45c9f58e0/pipeline-braille-utils/dotify-utils/dotify-formatter/src/main/java/org/daisy/pipeline/braille/dotify/impl/BrailleFilterFactoryImpl.java#L164))~~ `org.daisy.pipeline.braille.dotify.impl.NumberBrailleTranslator` ("VALID_INPUT")
  - Support other outputs than PEF

**Comment by josteinaj** [comment]
I've now added a post-processing XSLT for the preview so that numbers are rendered as numbers, ÆØÅ and æøå are rendered properly, and characters should have the correct upper case / lower case (words in all upper case that are hyphenated won't have their last part rendered in upper case though).

We could do the "not all braille characters needs to be translated to ascii" bullet point I mentioned at first there as well, but I think that would require some more thought as to which characters should be affected.

It's also pretty straight forward during post processing to replace characters 1:1. For instance, we could make punctuation marks and commas actually look like puncuation marks and commas if we want to.

See: 77f5b933ecd87c50c4f7740099f7e1d041ddcef4

**Comment by bertfrees** [comment]
I can't open the preview anymore.

In order to make it work I need to change `<script type="text/javascript" src="pef-preview.js"/>` to `<script type="text/javascript" src="pef-preview.js"></script>`.

**Comment by bertfrees** [comment]
And also `<span class="bookmark" id="x"/>` to `<span class="bookmark" id="x"></span>`.

**Comment by josteinaj** [comment]
Ah, I see. `post-process-preview.xsl` should have had a `<xsl:output indent="no" method="xhtml"/>`.
