### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#26]

**Comment by KariRudjord** [comment]
Notes working fine, but there are some problems:
Heading "Fotnoter" should be added on top of the first note in end of volume. 
With test job 506 (using 558096.xml, a regular book) heading is missing. 

With test job 507 (using Testbok.DTBook.XMLelements.xml, my test book) the heading is present, but notes have strange behaviour, repeating on next page without heading.

**Comment by bertfrees** [comment]
I have see in the default CSS that there is supposed to be a fallback mechanism for notes, i.e.: first try footnotes, and if they don't fit in the footnotes area, fall back to endnotes. However it was not implemented correctly. Endnotes were implemented [here](https://github.com/nlbdev/pipeline-mod-nlb/commit/94e20fa), footnotes [here](https://github.com/nlbdev/pipeline-mod-nlb/commit/4e5fcc6) but the latter doesn't work (and there is no test either).

Kari says she liked the fallback mechanism, but she doesn't want to put any more work in it because in fiction notes are not used a lot, and when we produce other books, it can be practical to have them collected in back of volume (or book).

So for now I'll (remove) the broken fallback code from the CSS. When you want it we add it back properly. I'll also create an option to choose between volume notes (default), footnotes and book notes (end of entire book).

**Comment by KariRudjord** [comment]
Make option for foot notes and book notes (in end of entire book) and volume end notes as standard. @bertfrees

**Comment by bertfrees** [comment]
@KariRudjord Adding a heading "Fotnoter" to the notes sections of volumes is possible, however there is one issue: when a volume does not have any notes, there will be a heading but no notes. Is this a problem?

**Comment by bertfrees** [comment]
@KariRudjord What should be the text for the notes option (in Norwegian)?

**Comment by KariRudjord** [comment]
Noter nederst på side
Noter bak i hefte (default)
Noter bak i boken

When I choose "Inkluder noter" false  (to leave out notes in a production), the note ref is still in the text and in the end of volume there are the headline "Fotnoter" but no notes, but on the next page there are notes. I is quite strange, @bertfrees . Job 527

**Comment by bertfrees** [comment]
The `include-notes` option was implemented [here](https://github.com/nlbdev/pipeline-mod-nlb/commit/5ce88d0). It looks a bit strange. I can fix it but what exactly is it supposed to do? Why was it called "include-note-references" before? It was renamed to "include-notes" while it is still simply passed on to the generic script as "include-note-references" ([here](https://github.com/nlbdev/pipeline-mod-nlb/commit/142dac6)). @josteinaj? They can't have a different name and the same meaning. Note that the "include-note-references" option was added on request of NLB (see [google doc "Configuration and user interface"](https://docs.google.com/document/d/1mOH7C0jj-NzZ1ZlzwqEUIklzJN0Z8IPhVNJL3-QVKYs/edit#heading=h.7d1t9i357i7a)) so if a rename is desirable it should be done in the generic script (or simply remove it from the generic script altogether).

**Comment by josteinaj** [comment]
We probably renamed it to better reflect what it actually does. We could rename it back (keeping the nicename), or rename/remove it in the generic script. Either way is fine for us.

In the CSS, the `include-note-references` only affects the actual notes, not the note references. I'll have a look at the note/noteref CSS.

**Comment by bertfrees** [comment]
Removing it in the generic script is easiest I think.

I'm also working on the CSS now, to implement the note section title and the notes-placement option.

**Comment by josteinaj** [comment]
Oh, ok. I'll wait a bit with the notes CSS then (haven't done much yet anyway).

**Comment by bertfrees** [comment]
> Adding a heading "Fotnoter" to the notes sections of volumes is possible, however there is one issue: when a volume does not have any notes, there will be a heading but no notes

Never mind, this is not true. There is no issue.

**Comment by bertfrees** [comment]
I have committed some changes to the CSS. @josteinaj could you plean have a quick look and see if I got it right?

**Comment by josteinaj** [comment]
@KariRudjord this looks like an old issue. Footnotes are working now, right?
