### ISSUE TITLE
Braille pages start on 0 at every new section (in PEF)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#56]
*from Trello*

Odd numbers appear on left side.

**Comment by bertfrees** [comment]
Which test can I use for this?

**Comment by josteinaj** [comment]
Does this always happen or just for some books. @KariRudjord @matskober if you can send me a (preferably small) book where this happens then I can create an automated test for it.

**Comment by matskober** [comment]
To me it seems to happen constantly.

**Comment by bertfrees** [comment]
The unit tests show that in some cases the page number is indeed 0. I'll investigate why that happens. It only seems to happen in the bodymatter though. It also does not always happen for every new section.

**Comment by bertfrees** [comment]
There is a rule (originally added in https://github.com/nlbdev/pipeline-mod-nlb/commit/1c259220d48a88396572d6a9425b84d96871b7af) in the CSS that says:
```css
bodymatter, ... {
    page: body;
    counter-set: page;
}
```

This rule is responsible for setting the initial page number to 0. This may have been more logical, because the page counter is incremented automatically, however it is not incremented automatically the first time. Thus it needs to be set to 1: `counter-set: page 1`.

I have changed the default CSS.
