### ISSUE TITLE
Should words in all capital letters be uncontracted?

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#74]
There's a rule in the latest version of the norwegian liblouis table saying that words in uppercase should not be contracted. Is that fine?

**Comment by matskober** [comment]
I believe that is a bad rule, given the quality of the Nordic EPUBs; they often have "non-semantic capitals" (as visual styling) in headings, blockquotes, the first words of chapters, etc. Also in children's  literature capital letters may be used as a way to emphasis bits of text, like SCREAMING. According to OUP, capitalisation is not preferable used as emphasis in braille (page 24 in "Håndbok for ...") . If we are to keep the capitalisation as it is in the source file (as consensus seems to be among the Nordic countries cooperating), and not edit this somehow before producing Braille,  NOT (sic) to contract capitalised word or word groups, would appear as yet another emphasis. (Often there are `<strong>` tags in play at these text elements, so it will be three "layers" of emphasis on these incidents.) A bit over the top, maybe?
@bertfrees @josteinaj @KariRudjord @olavindergaard  @usama49

**Comment by josteinaj** [comment]
How about we remove any `<strong>` or `<em>` tags from all-capital words/sentences before converting, would it then be ok to keep the rule? Is this mainly a problem with our source files and not with the braille table itself?

**Comment by bertfrees** [comment]
Of course I agree with Jostein regarding removing the strong/em tags, but if I understand Mats correctly the Nordic countries have decided not to do this.

The rule could be removed from the table (actually we would make two tables, one with the rule and one without), however I'm not sure the rule is always redundant. There must be a good reason why Bue added it. Norwegian is even mentioned in the [documentation](http://liblouis.org/documentation/liblouis.html#Special-Processing-Opcodes).

**Comment by matskober** [comment]
I guess this is a "political" question mainly; there is one school claiming that the Braille version should try to represent everything found in the visual / print book - including styling such as strong and capitals, even in headings. In the other end we find those who want the braille version to stripped for visual styling, only passing on "semantic styling" to the braille.  OUP's attitude on the subject leans to the latter; we have received critics on the capitalisation in the headings, on the capitals in the beginning of chapters and of the use of capitals as emphasis in the running text.

In this case, though, the question was whether or not to keep a rule saying not to contract capitalised words. In my opinion we should dump the rule, because not to contract them would emphasis them (the styling) further. Given the context above, not to contract would, to a large extent, be to emphasis the visual style "contamination" in the source file.  I'm pretty sure that is not the intent behind the rule; may be it's addressing other capitalised incidents, such as acronyms, logos?

**Comment by bertfrees** [comment]
Maybe we should ask Bue why exactly the rule was added. There doesn't seem to be a strong use case.

Do you guys mark up acronyms? For acronyms it does make sense to not contract.

Also I have found an example where it is problematic to disable the rule, although I admit it's a real corner case: mixed caps inside a contraction.

**Comment by matskober** [comment]
My point is that we should contract capitalised words and group of words, due to the fact that most of them would not be capitalised if the visual styling had been removed.

**Comment by bertfrees** [comment]
Yes I understand. But still I'm curious what the reasons were for adding the rule. @BueVest can you help us out here?

**Comment by BueVest** [comment]
Hi guys,
The capsnocont opcode has been described in the documentation for very long, mentioning the Norwegian tables as an example of where the rule is used. I remember seeing it already the first time I looked at the documentation.
Also,  One of the Norwegian guys on the liblouis mailing list mentioned it a couple of times on the list. So, when I fixed the opcode, I offered to implement the rule in the Norwegian tables for him.

I am very sorry if this has caused any trouble, political or otherwise (smile). Reverting the change is merely a question of deleting or commenting out a single line.
 
Bue

**Comment by bertfrees** [comment]
OK thanks for the explanation Bue.

Don't worry you didn't cause any trouble. We know it's very easy to disable the rule. But I still wanted to know about the reasons the rule exists. I guess we should talk to Lars then? I think we should try to come to an agreement with Lars for the sake of uniformity.

**Comment by matskober** [comment]
Did Lars or Kristin give any feedback on this?

**Comment by josteinaj** [comment]
Lars requested this rule, but we don't have an explaination for it yet. Don't know if Liv Kristin has given feedback yet.

Anyway, could we agree that whatever we decide, we should use the official liblouis version instead of our own table, and so if we want to remove this rule, we should do it in the liblouis project?

**Comment by josteinaj** [comment]
We will use the official liblouis table which comes bundled with Pipeline 2.
