### ISSUE TITLE
Avoid orphaned headlines (headline at the end of a volume)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#88]
Example:

```xml
<level1>
    <h1>...</h1>
    <p>...</p>
    <level2>
        <h2>...</h2>
```

Here, the h1 and p has a tendency to end up in the volume before level2.

**Comment by josteinaj** [comment]
See pending test here: https://github.com/nlbdev/pipeline/blob/5011f451edd65e13f8835a28e450375fa0d9ed4b/modules/nlb/book-to-pef/src/test/xprocspec/test_dtbook-to-pef_volume-breaking.xprocspec#L758

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-mod-braille/issues/159

**Comment by bertfrees** [comment]
Related: https://github.com/nlbdev/pipeline/issues/91

**Comment by bertfrees** [comment]
We ended up not using `-obfl-keep-with-next-sheets`. Instead we simply treat the first level2 the same as the parent level1, so that there is no preference for breaking before the level2. Because a break before the level1 is more preferable than a break inside the level1, the chance of a break happening inside the level1 before the first level2 is smaller than the chance of a break happening inside the level2. This is exactly what we want.

(**EDIT**: The reasoning here is that the closer you get to a preferred break point, the bigger the chance is that you "snap" to that break point. Or in other words, it is more likely that an actual break point lies further away from a preferred one than close but not on it.)

**Comment by josteinaj** [comment]
@KariRudjord and I discussed this today. We agreed that it should be as described by @bertfrees in the previous comment (https://github.com/nlbdev/pipeline/issues/88#issuecomment-342846757). In addition, we want to try having a `-obfl-keep-with-next-sheets: 1;` for the first child sections/levels to prevent orphaned headlines.

**Comment by bertfrees** [comment]
@josteinaj What is the current status? I'm still assigned, but I see you updated and simplified the volume breaking CSS last week. The test ("Content at start of part should be in same volume as first descendant chapter") still passes. You didn't add the `-obfl-keep-with-next-sheets` yet though. Is that still the goal?

**Comment by josteinaj** [comment]
@bertfrees I'll unassign you. I think I originally assigned this to you in a bulk of other volume breaking issues. Adding `-obfl-keep-with-next-sheets` is still the goal.

**Comment by josteinaj** [comment]
As mentioned in https://github.com/nlbdev/pipeline/issues/88#issuecomment-343148179, we want to try avoiding orphaned headlines by using `-obfl-keep-with-next-sheets: 1;`. This should only be needed for the first amongst sibling sections, i.e. `//level1[1]`, `//level1/level2[1]`, `//level1/level2/level3[1]`, etc. where the `-obfl-keep` priority is the same for all levels.

I've pushed a test for orphaned headlines.

**Comment by bertfrees** [comment]
I've added the following CSS: https://github.com/nlbdev/pipeline/blob/630bc4376d541e3106805b1773c420589c0fa41d/modules/nlb/book-to-pef/src/main/resources/css/nlb-default.scss#L167-L174

Note that for very small sections (smaller than one sheet) this might have an undesired effect, but I suggest you try it first. A solution could be to set `keep-with-next-sheets: 1` only on the highest levels, or to set it based on some heuristic that involves guessing the size of the section.

Also note that `keep-with-next-sheets` will not work anymore across level1's because https://github.com/nlbdev/pipeline/issues/91 got dropped (land evel1's start on a new right-hand page), but I don't expect that to be issue because I assume such short level1's are not so common.

**Comment by josteinaj** [comment]
So for this to be a problem, I suppose there would for instance have to be a series of very short level2s containing very short level3s. And there would have to be enough of them so that they fill an entire volume... Right?

Would there potentially be some volume breaking exception, or would it just result in bad volume breaking?

**Comment by bertfrees** [comment]
Right, I think that's what I mean. But even if there are not enough to fill an entire volume, it may result in sheets being kept together when not desired. I don't think it would cause exceptions. Just non-optimal volume breaking.

**Comment by josteinaj** [comment]
Ok. I'll move this to "Ready for test", and we'll see what @KariRudjord has to say.

**Comment by josteinaj** [comment]
...or "Ready for deployment" for now. I suppose this should wait until the system is fully updated to the latest DP2 release.

**Comment by KariRudjord** [comment]
In DTBook 561894 first volume ends with the page Part 1. It should be the first page in vol. 2. (much text in preface in this partiuclar book) @josteinaj will add some rule saying keep with next page to avoid this.

**Comment by josteinaj** [comment]
We agreed some weeks ago that instead of moving content from the start of a part or chapter into the same volume as first descendant chapter or subchapter, we want to maximize the number of pages used in each volume. However, if the content is very short (for instance just a headline), then we still want to make sure that it is in the same volume as the first following content section, so that we avoid orphaned headlines. I'm trying to get this working using the `-obfl-keep-with-next-sheets` CSS property, but it doesn't work in this particular case. See issue #91.
